apiVersion: v1
kind: ConfigMap
metadata:
  name: uas-config
  namespace: uas-service
data:
  DB_HOST: "mysql"
  DB_USER: "root"
  DB_NAME: "uas_service"
  RABBIT_URL: "amqp://rabbitmq"
---
apiVersion: v1
kind: Secret
metadata:
  name: uas-secrets
  namespace: uas-service
type: Opaque
stringData:
  DB_PASSWORD: "root"
  JWT_SECRET: "your-secret-key-change-in-production"


